# Generated by Django 3.0.5 on 2020-05-26 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boleta',
            options={'verbose_name': 'Boleta', 'verbose_name_plural': 'Boletas'},
        ),
    ]
