# Generated by Django 3.0.5 on 2020-05-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0002_auto_20200525_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle',
            options={'verbose_name': 'Detalle de venta', 'verbose_name_plural': 'Detalles de ventas'},
        ),
    ]
