# Generated by Django 3.0.5 on 2020-05-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_proveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Tipo de categoria', 'verbose_name_plural': 'Tipos de categorias'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Tipo de producto', 'verbose_name_plural': 'Tipos de productos'},
        ),
    ]
