# Generated by Django 2.2.2 on 2020-05-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20200525_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='garantia',
            field=models.CharField(default=1, max_length=50, verbose_name='Garantia'),
            preserve_default=False,
        ),
    ]
