# Generated by Django 3.0.5 on 2020-05-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_auto_20200519_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
