# Generated by Django 3.0.5 on 2020-05-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
    ]
