# Generated by Django 3.0.5 on 2020-05-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0002_auto_20200525_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucion',
            options={'verbose_name': 'Tipo de devolución', 'verbose_name_plural': 'Tipos de devoluciones'},
        ),
    ]
