# Generated by Django 3.0.5 on 2020-05-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=8, verbose_name='Telefono')),
                ('nit', models.CharField(blank=True, default='C/F', max_length=12, null=True, verbose_name='NIT')),
            ],
        ),
    ]
